// --- Kitchen Studio V2: language, units, recipe ideas, live basket estimate & expanded appliance library ---
state.profile.language=state.profile.language||localStorage.getItem('miseLanguage')||'fr';
state.profile.units=state.profile.units||localStorage.getItem('miseUnits')||'metric';
state.ideaOffset=0;
state.applianceFilter='all';

const UI={
  fr:{days:['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi','Dimanche'],meals:{breakfast:'Petit-déjeuner',lunch:'Déjeuner',dinner:'Dîner'},week:'Semaine du',recipe:'Recette',protein:'Protéiné',calories:'Calories',proteins:'Protéines',carbs:'Glucides',fat:'Lipides',classic:'Plaques / four classique',uses:'utilisations',estimate:'Est.',all:'Tous',guide:'Guide →',modes:'modes répertoriés',appliances:'appareils'},
  en:{days:['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],meals:{breakfast:'Breakfast',lunch:'Lunch',dinner:'Dinner'},week:'Week of',recipe:'Recipe',protein:'High protein',calories:'Calories',proteins:'Protein',carbs:'Carbs',fat:'Fat',classic:'Stovetop / conventional oven',uses:'uses',estimate:'Est.',all:'All',guide:'Guide →',modes:'listed modes',appliances:'appliances'}
};
const RECIPE_EN={
'overnight-oats':{name:'Berry overnight oats',tip:'Prep 2–3 jars at once for busy mornings.',steps:['Mix oats, yogurt, milk and chia in a jar.','Add the berries.','Refrigerate at least 4 hours. Add honey just before eating.']},
'egg-toast':{name:'Egg & avocado toast',tip:'Use the other half of the avocado at lunch the same day.',steps:['Toast the bread.','Cook the eggs to your preference.','Mash avocado with lemon, season lightly, then assemble with feta.']},
'protein-pancakes':{name:'Banana & skyr protein pancakes',tip:'The batter can be made the night before.',steps:['Blend or mash banana with egg, oats, skyr and baking powder.','Cook small pancakes 2–3 minutes per side over medium heat.','Serve with cinnamon and fruit.']},
'chicken-bowl':{name:'Lemon chicken & feta bowl',tip:'Cook a second portion of chicken for tomorrow’s lunch.',steps:['Season chicken with lemon, salt, pepper and a little oil.','Cook using the selected appliance until fully cooked.','Chop cucumber and tomatoes. Reheat rice.','Slice chicken and assemble with feta and lemon juice.']},
'salmon-rice':{name:'Miso salmon, rice & broccoli',tip:'Save some rice for tomorrow’s fried rice.',steps:['Mix miso, soy and honey, then brush over salmon.','Cook salmon and broccoli with your selected appliance.','Reheat rice and serve with sesame.']},
'turkey-wrap':{name:'Turkey, avocado & crunch wrap',tip:'Great for a portable lunch; keep the sauce separate if prepping ahead.',steps:['Mix yogurt with lemon, salt and pepper.','Fill tortilla with lettuce, tomato, avocado and turkey.','Add sauce, roll tightly and cut in half.']},
'chicken-pasta':{name:'Creamy tomato chicken pasta',tip:'Stir yogurt in off the heat to keep the sauce smooth.',steps:['Cook pasta al dente and reserve some pasta water.','Cook chicken, then slice.','Add tomato sauce and spinach, then lower heat.','Off the heat, stir in yogurt and a splash of pasta water. Add pasta, chicken and parmesan.']},
'tofu-bowl':{name:'Crispy sesame tofu bowl',tip:'Press tofu for 10 minutes before cooking for a better texture.',steps:['Press and cube the tofu.','Toss with soy sauce and a little starch if available.','Cook until crisp, then serve over rice with vegetables and edamame.']},
'greek-salad':{name:'Big Greek chickpea salad',tip:'Add an egg or chicken if you want even more protein.',steps:['Rinse chickpeas.','Chop cucumber and tomatoes.','Mix with feta, olives, lemon and a drizzle of oil.','Serve with toasted pita.']},
'fried-rice':{name:'Chicken & edamame fried rice',tip:'Day-old rice is ideal here and prevents leftovers from going to waste.',steps:['Stir-fry carrot and edamame over high heat.','Add cold rice and let it toast slightly.','Push aside, scramble the egg, then combine.','Add chicken, soy sauce and sesame oil.']},
'sheet-pan':{name:'Paprika chicken & roasted vegetables',tip:'Double the vegetables and reuse them in an omelet or bowl tomorrow.',steps:['Cut vegetables and potatoes into even pieces.','Toss with paprika, oil, salt and pepper.','If your appliance is small, start potatoes a few minutes before chicken and vegetables.','Cook until chicken is fully cooked and vegetables are browned.']},
'yogurt-bowl':{name:'Skyr bowl with banana & granola',tip:'Choose a lower-sugar granola if the banana and skyr are sweet enough.',steps:['Spoon skyr into a bowl.','Add banana, granola and almond butter.','Finish with cinnamon.']}
};
const ING_EN={
'Flocons d’avoine':'Rolled oats','Skyr ou Greek yogurt':'Skyr or Greek yogurt','Lait':'Milk','Fruits rouges':'Berries','Graines de chia':'Chia seeds','Miel':'Honey','Pain complet':'Whole-grain bread','Œufs':'Eggs','Œuf':'Egg','Avocat':'Avocado','Feta':'Feta','Citron':'Lemon','Banane':'Banana','Skyr':'Skyr','Levure':'Baking powder','Cannelle':'Cinnamon','Blanc de poulet':'Chicken breast','Poulet':'Chicken','Poulet cuit':'Cooked chicken','Riz cuit':'Cooked rice','Riz cuit froid':'Cold cooked rice','Concombre':'Cucumber','Tomates cerises':'Cherry tomatoes','Huile d’olive':'Olive oil','Filet de saumon':'Salmon fillet','Brocoli':'Broccoli','Miso':'Miso','Sauce soja':'Soy sauce','Sésame':'Sesame seeds','Tortilla complète':'Whole-wheat tortilla','Dinde cuite':'Cooked turkey','Salade':'Lettuce','Tomate':'Tomato','Greek yogurt':'Greek yogurt','Pâtes':'Pasta','Passata tomate':'Tomato passata','Épinards':'Spinach','Parmesan':'Parmesan','Tofu ferme':'Firm tofu','Carotte':'Carrot','Edamame':'Edamame','Pois chiches':'Chickpeas','Tomates':'Tomatoes','Olives':'Olives','Pita':'Pita','Huile sésame':'Sesame oil','Pommes de terre':'Potatoes','Courgette':'Zucchini','Poivron':'Bell pepper','Paprika':'Paprika','Granola':'Granola','Beurre d’amande':'Almond butter'};
const CUP_GRAMS={
'flocons d’avoine':80,'skyr ou greek yogurt':245,'skyr':245,'greek yogurt':245,'fruits rouges':145,'riz cuit':195,'riz cuit froid':195,'tomates cerises':150,'brocoli':90,'salade':50,'épinards':30,'edamame':155,'pois chiches':164,'tomates':180,'granola':100,'passata tomate':245
};
const PRICE_RULES=[
[/saumon/i,8.49],[/poulet/i,6.49],[/dinde/i,5.99],[/tofu/i,3.49],[/œuf/i,4.49],[/skyr|yogurt|yaourt/i,5.49],[/feta|parmesan/i,4.99],[/riz/i,3.49],[/pâtes/i,2.49],[/avoine/i,4.29],[/pain|pita|tortilla/i,3.99],[/avocat/i,1.69],[/brocoli/i,2.99],[/concombre/i,1.49],[/tomat/i,3.49],[/banane/i,1.79],[/fruits rouges/i,4.99],[/pois chiches/i,1.79],[/edamame/i,3.49],[/pomme de terre/i,3.99],[/courgette|poivron|carotte|épinards|salade/i,2.49],[/huile/i,6.99],[/miso|soja|sésame/i,4.49],[/miel/i,5.99],[/chia/i,6.49],[/granola/i,4.99],[/citron/i,1.49],[/olive/i,3.99],[/lait/i,3.99],[/levure|cannelle|paprika/i,2.49],[/beurre d’amande/i,7.49]
];
const STORE_MULTIPLIER={'Whole Foods Market':1.16,"Trader Joe’s":.94,'Safeway':1.04,'QFC':1.03,'Costco':1.08,'Target':.98,'Carrefour':1,'Monoprix':1.14,'Auchan':.95};
const APPLIANCE_DESC_EN={
'cosori-turboblaze-6':'6.2 L, 90–450°F and 10 functions with precise airflow control by mode.','instant-vortex-plus-6':'6QT ClearCook with 6 cooking functions and a viewing window.','ninja-dz550':'Two independent 5QT cooking zones for cooking two foods at once.','philips-hd9650':'XXL air fryer with Rapid Air technology, family capacity and keep-warm mode.','cuisinart-toa70':'8-function air fryer toaster oven with reversible grill/griddle and up to 450°F.','breville-bov900':'Countertop oven with 13 smart functions, Air Fry, dehydrate and super convection.','generic-oven':'Generic profile for oven temperature, preheating, convection and broiling.','generic-stovetop':'Profile for pans, pots, wok and heat-level guidance.','generic-microwave':'For reheating, defrosting and quick cooking based on appliance wattage.','generic-rice-cooker':'For white rice, brown rice, quinoa and keep-warm cycles.','generic-multicooker':'Pressure-cooking profile for soups, grains, legumes, slow cook and sauté.','generic-blender':'For smoothies, sauces, blended soups, pesto and batters.','generic-slow-cooker':'For stews, chili, pulled meats and long meal-prep cooks.','generic-grill':'For searing meat, fish, vegetables and pressed sandwiches.'
};
function isEN(){return state.profile.language==='en'}
function txt(fr,en){return isEN()?en:fr}
function recipeText(r){const e=RECIPE_EN[r.id]||{};return {name:isEN()?(e.name||r.name):r.name,tip:isEN()?(e.tip||r.tip):r.tip,steps:isEN()?(e.steps||r.steps):r.steps}}
function ingredientName(name){return isEN()?(ING_EN[name]||name):name}
function parseNumber(raw){const map={'¼':.25,'⅓':1/3,'½':.5,'⅔':2/3,'¾':.75,'1½':1.5};if(map[raw]!=null)return map[raw];return Number(raw)}
function formatQty(name,qty){
  if(state.profile.units==='cups')return qty;
  const q=qty.trim();
  let m=q.match(/^(¼|⅓|½|⅔|¾|1½|\d+(?:\.\d+)?)\s*(cups?|cup)\b/i);
  if(m){const n=parseNumber(m[1]),key=name.toLowerCase(),gpc=CUP_GRAMS[key];return gpc?`≈ ${Math.round(n*gpc)} g`:`≈ ${Math.round(n*240)} ml`}
  m=q.match(/^(¼|⅓|½|⅔|¾|1½|\d+(?:\.\d+)?)\s*oz\b/i);if(m)return `≈ ${Math.round(parseNumber(m[1])*28.35)} g`;
  m=q.match(/^(¼|⅓|½|⅔|¾|1½|\d+(?:\.\d+)?)\s*tbsp\b/i);if(m)return `≈ ${Math.round(parseNumber(m[1])*15)} ml`;
  m=q.match(/^(¼|⅓|½|⅔|¾|1½|\d+(?:\.\d+)?)\s*tsp\b/i);if(m)return `≈ ${Math.round(parseNumber(m[1])*5)} ml`;
  return q.replace('pinch',txt('pincée','pinch'));
}
function basePrice(name){const found=PRICE_RULES.find(([re])=>re.test(name));return found?found[1]:2.49}
function currencyInfo(){const euro=['Carrefour','Monoprix','Auchan'].includes(state.profile.store);return euro?{symbol:'€',locale:'fr-FR',currency:'EUR'}:{symbol:'$',locale:'en-US',currency:'USD'}}
function estimateItemPrice(name){return basePrice(name)*(STORE_MULTIPLIER[state.profile.store]||1)}
function estimatedCartTotal(){return aggregateShopping().filter(x=>!state.shopChecked.has(x.name.toLowerCase().replace(/\s/g,'-'))).reduce((sum,x)=>sum+estimateItemPrice(x.name),0)}
function money(v){const c=currencyInfo();return new Intl.NumberFormat(c.locale,{style:'currency',currency:c.currency,maximumFractionDigits:2}).format(v)}
function renderMoneyBig(v){const c=currencyInfo(),parts=v.toFixed(2).split('.');$('#cartEstimate').innerHTML=c.symbol==='€'?`${parts[0]}<span>,${parts[1]} €</span>`:`$${parts[0]}<span>.${parts[1]}</span>`}
function currentDays(){return UI[state.profile.language].days}
function currentMeals(){return UI[state.profile.language].meals}
fmtDate=function(d){return d.toLocaleDateString(isEN()?'en-US':'fr-FR',{day:'numeric',month:'short'}).replace('.','')}
updateWeekHeader=function(){const a=dateForDay(0),b=dateForDay(6),locale=isEN()?'en-US':'fr-FR';$('#weekLabel').textContent=`${UI[state.profile.language].week} ${a.toLocaleDateString(locale,{day:'numeric',month:'long'})}`;$('#weekRange').textContent=isEN()?`${a.toLocaleDateString(locale,{month:'short',day:'numeric'})}–${b.toLocaleDateString(locale,{month:'short',day:'numeric'})}`:`${a.getDate()}–${b.getDate()} ${b.toLocaleDateString(locale,{month:'long'})}`}
renderWeek=function(){const grid=$('#weekGrid');grid.innerHTML='';const days=currentDays(),labels=currentMeals();state.plan.forEach((meals,d)=>{const col=document.createElement('div');col.className='day-col';const date=dateForDay(d);col.innerHTML=`<div class="day-head ${date.getDate()===23&&state.weekOffset===0?'today':''}"><strong>${days[d]}</strong><small>${fmtDate(date)}</small></div>`;meals.forEach((id,slotIndex)=>{const r=recipeById(id),rt=recipeText(r),slot=['breakfast','lunch','dinner'][slotIndex],key=`${d}-${slotIndex}`;const card=document.createElement('article');card.className=`meal-card ${slot==='dinner'?'dinner':''} ${state.selected.has(key)?'selected':''}`;card.dataset.key=key;card.dataset.id=id;card.innerHTML=`<span class="selected-dot"></span><div class="meal-slot">${labels[slot]}</div><h4>${rt.name}</h4><div class="meal-foot"><span>${r.time} min · ${r.protein}g ${isEN()?'protein':'prot.'}</span><span class="kcal">${r.kcal} kcal</span></div>`;card.addEventListener('click',e=>{if(e.shiftKey){toggleSelect(key);return}openRecipe(r,`${days[d]} ${date.getDate()} · ${labels[slot]}`)});card.addEventListener('contextmenu',e=>{e.preventDefault();toggleSelect(key)});col.appendChild(card)});grid.appendChild(col)});updateWeekHeader();renderShopping();renderRecipeIdeas()}
populateApplianceSelect=function(){const sel=$('#detailApplianceSelect');if(!sel)return;sel.innerHTML=`<option value="default">${UI[state.profile.language].classic}</option>${appliances.map(a=>`<option value="${a.id}">${a.brand} ${a.model}</option>`).join('')}`;const fav=appliances.find(a=>a.favorite)||appliances[0];if(fav)sel.value=fav.id}
openRecipe=function(r,slotText){currentRecipe=r;const rt=recipeText(r);$('#detailTitle').textContent=rt.name;$('#detailMealSlot').textContent=slotText||UI[state.profile.language].recipe;$('#detailTags').textContent=`${r.tags.includes('high-protein')?UI[state.profile.language].protein+' · ':''}${r.time} min`;$('#detailSubtitle').textContent=rt.tip;$('#detailPhoto').style.backgroundImage=`linear-gradient(to top,rgba(0,0,0,.25),transparent 55%),url('${r.image}')`;$('#detailMacros').innerHTML=[[UI[state.profile.language].calories,`${r.kcal} kcal`],[UI[state.profile.language].proteins,`${r.protein} g`],[UI[state.profile.language].carbs,`${r.carbs} g`],[UI[state.profile.language].fat,`${r.fat} g`]].map(x=>`<div class="macro"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('');$('#detailIngredients').innerHTML=r.ingredients.map(([name,qty])=>`<div class="ingredient-row"><span>${ingredientName(name)}</span><span>${formatQty(name,qty)}</span></div>`).join('');$('#detailSteps').innerHTML=rt.steps.map(step=>`<li>${step}</li>`).join('');$('#detailTip').textContent=rt.tip;populateApplianceSelect();updateRecipeMethod();openModal($('#recipeModal'))}
simplifyQty=function(name,qtys){if(qtys.length===1)return formatQty(name,qtys[0]);return `${qtys.length} ${UI[state.profile.language].uses}`}
function categoryLabel(cat){if(!isEN())return cat;return {'Protéines':'Protein','Épicerie & féculents':'Pantry & grains','Frais & laitages':'Dairy & chilled','Placard':'Pantry','Fruits & légumes':'Fruit & vegetables'}[cat]||cat}
productSuggestion=function(){const store=state.profile.store||txt('votre magasin','your store');return isEN()?`Match to a real product at ${store}`:`À faire correspondre aux produits de ${store}`}
renderShopping=function(){const items=aggregateShopping(),groups={};items.forEach(it=>{const c=categorize(it.name);(groups[c]??=[]).push({...it,key:it.name.toLowerCase().replace(/\s/g,'-')})});$('#shoppingList').innerHTML=Object.entries(groups).map(([cat,arr])=>`<div class="shopping-category"><div class="shopping-category-title">${categoryLabel(cat)}</div>${arr.map(it=>`<label class="shop-row"><input class="shop-check" type="checkbox" data-shop="${it.key}" ${state.shopChecked.has(it.key)?'checked':''}><span class="shop-name"><strong>${ingredientName(it.name)}</strong><small>${productSuggestion()}</small></span><span class="shop-price">${money(estimateItemPrice(it.name))}</span><span class="shop-qty">${simplifyQty(it.name,it.qtys)}</span></label>`).join('')}</div>`).join('');$$('.shop-check').forEach(c=>c.addEventListener('change',()=>{c.checked?state.shopChecked.add(c.dataset.shop):state.shopChecked.delete(c.dataset.shop);localStorage.setItem('miseShopChecked',JSON.stringify([...state.shopChecked]));updateShoppingMeta()}));$('#shoppingCount').textContent=items.length;$('#cartItems').textContent=items.length;updateShoppingMeta()}
updateShoppingMeta=function(){const total=estimatedCartTotal();$('#pantryCount').textContent=state.shopChecked.size;renderMoneyBig(total);$('#budgetEstimate').textContent=`≈ ${money(total)}`}
renderRecipes=function(filter='all'){const list=RECIPES.filter(r=>filter==='all'||(filter==='quick'?r.time<=20:r.tags.includes(filter)));$('#recipeGrid').innerHTML=list.map(r=>{const rt=recipeText(r);return `<article class="recipe-tile" data-recipe="${r.id}"><div class="recipe-tile-photo" style="background-image:url('${r.image}')"><span>${r.time} min</span></div><div class="recipe-tile-body"><div class="eyebrow">${r.protein}g ${isEN()?'protein':'protéines'} · ${r.kcal} kcal</div><h3>${rt.name}</h3><div class="recipe-meta"><span>${r.tags.includes('airfryer')?'Air Fryer':txt('Cuisine simple','Simple cooking')}</span><span>${r.tags.includes('vegetarian')?txt('Végétarien','Vegetarian'):txt('Flexible','Flexible')}</span></div></div></article>`}).join('');$$('[data-recipe]').forEach(t=>t.addEventListener('click',()=>openRecipe(recipeById(t.dataset.recipe),txt('Carnet de recettes','Recipe book'))))}
function renderRecipeIdeas(){const used=new Set(state.plan.flat());let pool=RECIPES.filter(r=>!used.has(r.id));if(pool.length<4)pool=RECIPES;const picks=Array.from({length:4},(_,i)=>pool[(i+state.ideaOffset)%pool.length]);const box=$('#recipeIdeasGrid');if(!box)return;box.innerHTML=picks.map(r=>{const rt=recipeText(r);return `<article class="idea-card" data-idea="${r.id}"><div class="idea-photo" style="background-image:url('${r.image}')"></div><div><span>${r.time} min · ${r.protein}g ${isEN()?'protein':'prot.'}</span><h4>${rt.name}</h4><small>${r.tags.includes('vegetarian')?txt('Végétarien','Vegetarian'):r.tags.includes('airfryer')?'Air Fryer':txt('Rapide & simple','Quick & simple')}</small></div></article>`}).join('');$$('[data-idea]').forEach(c=>c.addEventListener('click',()=>openRecipe(recipeById(c.dataset.idea),txt('Idée recette','Recipe idea'))))}
renderAppliances=function(filter=state.applianceFilter||'all'){state.applianceFilter=filter;const fav=appliances.find(a=>a.favorite)||appliances[0];if(!fav)return;$('#favoriteApplianceName').textContent=`${fav.brand} ${fav.model}`;$('#favoriteApplianceMeta').textContent=isEN()?(APPLIANCE_DESC_EN[fav.id]||fav.description):fav.description;$('#favoriteModes').innerHTML=fav.modes.slice(0,6).map(m=>`<span>${m.name}</span>`).join('');$('#applianceCount').textContent=`${appliances.length} ${UI[state.profile.language].appliances}`;const list=filter==='all'?appliances:appliances.filter(a=>a.type===filter);$('#applianceGrid').innerHTML=list.map(a=>`<article class="appliance-card" data-appliance="${a.id}">${a.image?`<div class="appliance-photo-wrap"><img class="appliance-photo" src="${a.image}" alt="${a.brand} ${a.model}" loading="lazy"></div>`:`<div class="appliance-icon">${a.type==='Four'?'▣':a.type==='Plaques'?'◉':a.type==='Blender'?'◒':a.type==='Rice Cooker'?'◍':'◫'}</div>`}<div class="eyebrow">${a.type} · ${a.brand}</div><h3>${a.model}</h3><p>${isEN()?(APPLIANCE_DESC_EN[a.id]||a.description):a.description}</p><footer><span>${a.modes.length} ${UI[state.profile.language].modes}</span><span>${UI[state.profile.language].guide}</span></footer></article>`).join('');$$('[data-appliance]').forEach(c=>c.addEventListener('click',()=>openAppliance(c.dataset.appliance)));$('#viewFavoriteManual').onclick=()=>openAppliance(fav.id)}
openAppliance=function(id){const a=appliances.find(x=>x.id===id);if(!a)return;$('#applianceModalTitle').textContent=`${a.brand} ${a.model}`;$('#applianceModalDesc').textContent=isEN()?(APPLIANCE_DESC_EN[a.id]||a.description):a.description;$('#manualModeList').innerHTML=a.modes.map(m=>`<div class="manual-mode"><strong>${m.name} · ${m.preset}</strong><small>${m.goodFor}</small></div>`).join('');const link=$('#manualSourceLink');if(a.source){link.href=a.source;link.style.display='inline';link.textContent=txt('Ouvrir le guide officiel ↗','Open official guide ↗')}else{link.removeAttribute('href');link.style.display='none'}openModal($('#applianceModal'))}
updateStoreUI=function(){const store=state.profile.store||'Whole Foods Market',loc=state.profile.location||'Seattle, WA';$('#storePillName').textContent=`${store.replace(' Market','')} · ${loc.split(',')[0]}`;$('#shoppingStoreName').textContent=store;$('#shoppingLocation').textContent=loc;$('#profileSummary').textContent=`${state.profile.goal==='protein'?txt('Protéiné','High protein'):txt('Équilibré','Balanced')} · ${state.profile.servings||1} ${txt('pers.','serv.')}`;if($('#profileStore'))$('#profileStore').value=store;if($('#profileLocation'))$('#profileLocation').value=loc;updateShoppingMeta()}
function applyLanguage(){
  document.documentElement.lang=state.profile.language;
  $('#languageSelect').value=state.profile.language;$('#unitsSelect').value=state.profile.units;
  $('#languageLabel').textContent=txt('Langue','Language');$('#unitsLabel').textContent=txt('Mesures','Units');
  const nav=[['planner','⌂',txt('Ma semaine','My week')],['shopping','⌁',txt('Courses','Groceries')],['recipes','♨',txt('Recettes','Recipes')],['appliances','◫',txt('Mes appareils','My appliances')],['profile','◎',txt('Préférences','Preferences')]];
  nav.forEach(([page,icon,label])=>{const b=$(`.nav-item[data-page="${page}"]`);if(!b)return;const count=page==='shopping'?` <span class="nav-count" id="shoppingCount">${aggregateShopping().length}</span>`:'';b.innerHTML=`<span>${icon}</span> ${label}${count}`});
  $('.sidebar-card .eyebrow').textContent=txt('Chef IA','AI Chef');$('#openAiPrompt').textContent=txt('Parler au chef','Ask the chef');
  $('.profile-mini strong').textContent=txt('Mon profil','My profile');$('.store-pill small').textContent=txt('Courses chez','Shopping at');
  $('#page-planner .hero-row .eyebrow').textContent=txt('Votre brigade personnelle','Your personal kitchen crew');$('#page-planner h1').innerHTML=txt('Une semaine pensée<br/>comme un <em>menu de chef.</em>','A whole week planned<br/>like a <em>chef’s menu.</em>');$('#page-planner .lead').textContent=txt('Objectifs, allergies, budget, temps, envies, magasin et même votre Air Fryer : Mise assemble tout avant de choisir un seul plat.','Goals, allergies, budget, time, cravings, store and even your Air Fryer: Mise combines everything before choosing a single meal.');$('#weekSettings').textContent=txt('Critères de la semaine','Weekly preferences');$('#generateWeek').innerHTML=`<span>✦</span> ${txt('Composer avec l’IA','Plan with AI')}`;
  const insight=$$('#page-planner .insight-strip small');if(insight.length>=4){insight[0].textContent=txt('Cette semaine','This week');insight[1].textContent=txt('Objectif','Goal');insight[2].textContent=txt('Temps cuisine moyen','Avg. cook time');insight[3].textContent=txt('Budget estimé','Estimated cost')}$('#viewNutrition').textContent=txt('Voir nutrition →','View nutrition →');$('#regenerateSelected').textContent=txt('↻ Recomposer','↻ Regenerate');
  $('#page-shopping .eyebrow').textContent=txt('Liste intelligente','Smart list');$('#page-shopping h2').textContent=txt('Vos courses, déjà organisées.','Your groceries, already organized.');$('#page-shopping .page-head p').textContent=txt('Quantités regroupées pour toute la semaine. Cochez ce que vous avez déjà.','Quantities grouped for the whole week. Check off what you already have.');$('#clearChecked').textContent=txt('Masquer ce que j’ai','Hide what I have');$('#shopRealProducts').textContent=txt('Trouver les produits réels','Find real products');$('#shopRealProducts2').textContent=txt('Ouvrir la liste achetable','Open shoppable list');$('.cart-summary .eyebrow').textContent=txt('Panier estimé','Estimated basket');
  $('#recipesEyebrow').textContent=txt('Le carnet Mise','The Mise recipe book');$('#recipesTitle').textContent=txt('Des recettes qui connaissent votre cuisine.','Recipes that know your kitchen.');$('#recipesLead').textContent=txt('Chaque fiche s’adapte au matériel, au nombre de portions et aux préférences.','Every recipe adapts to your equipment, servings and preferences.');$('#recipeAiBtn').textContent=txt('✦ Inventer une recette','✦ Create a recipe');$('#ideasEyebrow').textContent=txt('Idées recettes','Recipe ideas');$('#ideasTitle').textContent=txt('Inspirations pour changer de votre semaine.','Fresh inspiration beyond this week’s plan.');$('#refreshIdeas').textContent=txt('↻ Nouvelles idées','↻ New ideas');
  const recipeFilters={all:txt('Toutes','All'),'high-protein':txt('Protéinées','High protein'),quick:'≤ 20 min',vegetarian:txt('Végé','Vegetarian'),airfryer:'Air Fryer'};$$('#page-recipes [data-filter]').forEach(b=>b.textContent=recipeFilters[b.dataset.filter]||b.textContent);
  const applianceFilters={all:txt('Tous','All'),'Air Fryer':'Air Fryers','Four':txt('Fours','Ovens'),'Multicuiseur':txt('Multicuiseurs','Multicookers'),'Rice Cooker':'Rice cookers','Blender':'Blenders','Micro-ondes':txt('Micro-ondes','Microwaves')};$$('[data-appliance-filter]').forEach(b=>b.textContent=applianceFilters[b.dataset.applianceFilter]||b.textContent);
  $('#page-appliances .page-head .eyebrow').textContent=txt('Votre vraie cuisine','Your real kitchen');$('#page-appliances .page-head h2').innerHTML=txt('L’IA cuisine avec <em>vos</em> appareils.','AI cooks with <em>your</em> appliances.');$('#page-appliances .page-head p').textContent=txt('Ajoutez marque + modèle. Les instructions changent selon les modes, plages de température et capacités réelles.','Add brand + model. Instructions change with the real modes, temperature ranges and capacity.');$('#addAppliance').textContent=txt('+ Ajouter un appareil','+ Add appliance');$('#applianceLibraryLabel').textContent=txt('Bibliothèque d’appareils','Appliance library');$('#viewFavoriteManual').textContent=txt('Voir modes & guide','View modes & guide');
  $('#page-profile .page-head .eyebrow').textContent=txt('Votre profil culinaire','Your cooking profile');$('#page-profile .page-head h2').textContent=txt('Plus Mise vous connaît, moins vous planifiez.','The more Mise knows you, the less you plan.');$('#page-profile .page-head p').textContent=txt('Ces préférences sont la base permanente. Les critères de semaine peuvent les modifier temporairement.','These are your permanent preferences. Weekly settings can temporarily override them.');$('#saveProfile').textContent=txt('Enregistrer','Save');
  $$('#page-profile .form-card h3').forEach((h,i)=>h.textContent=[[txt('Objectif & style','Goal & style'),txt('À respecter absolument','Must respect'),txt('Courses','Groceries'),txt('Comment je cuisine','How I cook')][i]||h.textContent]);
  $('#applianceModal .eyebrow').textContent=txt('Fiche appareil','Appliance profile');$('.manual-source strong').textContent=txt('Source constructeur','Manufacturer source');
  syncWizard();renderWeek();renderRecipes();renderRecipeIdeas();renderAppliances();populateApplianceSelect();updateStoreUI();if($('#recipeModal').open&&currentRecipe){const rt=recipeText(currentRecipe);$('#detailTitle').textContent=rt.name;$('#detailSubtitle').textContent=rt.tip;$('#detailIngredients').innerHTML=currentRecipe.ingredients.map(i=>`<div class="ingredient-row"><span>${ingredientName(i[0])}</span><span>${formatQty(i[0],i[1])}</span></div>`).join('');$('#detailSteps').innerHTML=rt.steps.map(x=>`<li>${x}</li>`).join('')}
}
$('#languageSelect').addEventListener('change',e=>{state.profile.language=e.target.value;localStorage.setItem('miseLanguage',state.profile.language);localStorage.setItem('miseProfile',JSON.stringify(state.profile));applyLanguage()});
$('#unitsSelect').addEventListener('change',e=>{state.profile.units=e.target.value;localStorage.setItem('miseUnits',state.profile.units);localStorage.setItem('miseProfile',JSON.stringify(state.profile));renderShopping();if($('#recipeModal').open&&currentRecipe){$('#detailIngredients').innerHTML=currentRecipe.ingredients.map(i=>`<div class="ingredient-row"><span>${ingredientName(i[0])}</span><span>${formatQty(i[0],i[1])}</span></div>`).join('')}showToast(txt('Mesures mises à jour.','Units updated.'))});
$('#refreshIdeas').addEventListener('click',()=>{state.ideaOffset=(state.ideaOffset+4)%RECIPES.length;renderRecipeIdeas()});
$$('[data-appliance-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-appliance-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderAppliances(b.dataset.applianceFilter)}));

applyLanguage();

