// Mise V12 — no-cook & microwave inspiration catalog
(function(){
  const tr=(fr,en)=>state.profile.language==='en'?en:fr;
  const fallbackImage=(needle)=>{
    const r=RECIPES.find(x=>(x.tags||[]).includes(needle))||RECIPES.find(x=>x.image);
    return r?.image||'';
  };
  const noCookImg=fallbackImage('salad');
  const breakfastImg=fallbackImage('breakfast')||noCookImg;
  const bowlImg=fallbackImage('bowl')||noCookImg;

  const EXTRA=[
    {id:'minimal-nocook-greek-chickpea',name:'Salade grecque pois chiches & feta',slot:'lunch',time:10,kcal:470,protein:24,carbs:44,fat:23,tags:['no-cook','salad','vegetarian','mediterranean'],image:noCookImg,ingredients:[['Pois chiches en conserve','¾ cup'],['Concombre','½'],['Tomates cerises','1 cup'],['Feta','1.5 oz'],['Huile d’olive','1 tsp']],steps:['Rincez les pois chiches.','Coupez les légumes.','Mélangez avec la feta et l’huile.'],tip:'Aucune cuisson nécessaire.',methods:{default:['Sans cuisson','10 min'],airfryer:['Sans cuisson','Aucune cuisson nécessaire']}},
    {id:'minimal-nocook-tuna-avocado-wrap',name:'Wrap thon avocat & crudités',slot:'lunch',time:8,kcal:510,protein:34,carbs:46,fat:21,tags:['no-cook','fish','quick'],image:bowlImg,ingredients:[['Tortilla complète','1'],['Thon en conserve','1 can'],['Avocat','½'],['Concombre','½ cup'],['Yaourt grec','2 tbsp']],steps:['Égouttez le thon.','Écrasez l’avocat avec le yaourt.','Garnissez la tortilla et roulez.'],tip:'Parfait quand vous n’avez aucun appareil.',methods:{default:['Sans cuisson','8 min'],airfryer:['Sans cuisson','Aucune cuisson nécessaire']}},
    {id:'minimal-nocook-skyr-berry',name:'Bowl skyr, fruits rouges & granola',slot:'breakfast',time:4,kcal:390,protein:29,carbs:47,fat:10,tags:['no-cook','breakfast','high-protein','vegetarian'],image:breakfastImg,ingredients:[['Skyr','1 cup'],['Fruits rouges','1 cup'],['Granola','¼ cup'],['Graines de chia','1 tbsp']],steps:['Versez le skyr dans un bol.','Ajoutez les fruits, le granola et les graines.'],tip:'Petit-déjeuner protéiné sans cuisson.',methods:{default:['Sans cuisson','4 min'],airfryer:['Sans cuisson','Aucune cuisson nécessaire']}},
    {id:'minimal-nocook-overnight-oats',name:'Overnight oats banane & chia',slot:'breakfast',time:5,kcal:430,protein:19,carbs:64,fat:12,tags:['no-cook','breakfast','vegetarian','meal-prep'],image:breakfastImg,ingredients:[['Flocons d’avoine','½ cup'],['Lait','½ cup'],['Yaourt grec','½ cup'],['Banane','½'],['Graines de chia','1 tbsp']],steps:['Mélangez tout dans un bocal.','Placez au frais pendant la nuit.'],tip:'Se prépare la veille, sans cuisson.',methods:{default:['Sans cuisson','5 min + repos'],airfryer:['Sans cuisson','Aucune cuisson nécessaire']}},
    {id:'minimal-nocook-hummus-wrap',name:'Wrap houmous, légumes & feta',slot:'lunch',time:7,kcal:450,protein:18,carbs:50,fat:20,tags:['no-cook','vegetarian','quick'],image:noCookImg,ingredients:[['Tortilla complète','1'],['Houmous','¼ cup'],['Concombre','½ cup'],['Poivron','½ cup'],['Feta','1 oz']],steps:['Étalez le houmous sur la tortilla.','Ajoutez légumes et feta.','Roulez et servez.'],tip:'Zéro cuisson et très peu de vaisselle.',methods:{default:['Sans cuisson','7 min'],airfryer:['Sans cuisson','Aucune cuisson nécessaire']}},
    {id:'minimal-nocook-caprese',name:'Caprese complète mozzarella & haricots blancs',slot:'lunch',time:8,kcal:480,protein:25,carbs:38,fat:25,tags:['no-cook','vegetarian','italian','salad'],image:noCookImg,ingredients:[['Tomates','1.5 cups'],['Mozzarella','3 oz'],['Haricots blancs en conserve','½ cup'],['Basilic','1 handful'],['Huile d’olive','1 tsp']],steps:['Égouttez les haricots.','Coupez tomates et mozzarella.','Assemblez avec basilic et huile.'],tip:'Une caprese plus rassasiante.',methods:{default:['Sans cuisson','8 min'],airfryer:['Sans cuisson','Aucune cuisson nécessaire']}},
    {id:'minimal-nocook-smoked-salmon-bagel',name:'Bagel saumon fumé & fromage frais',slot:'breakfast',time:6,kcal:470,protein:27,carbs:51,fat:18,tags:['no-cook','breakfast','fish'],image:breakfastImg,ingredients:[['Bagel complet','1'],['Saumon fumé','3 oz'],['Fromage frais','2 tbsp'],['Concombre','¼'],['Citron','¼']],steps:['Coupez le bagel.','Tartinez de fromage frais.','Ajoutez saumon, concombre et citron.'],tip:'Aucune cuisson nécessaire.',methods:{default:['Sans cuisson','6 min'],airfryer:['Sans cuisson','Aucune cuisson nécessaire']}},
    {id:'minimal-nocook-chicken-caesar-wrap',name:'Wrap Caesar au poulet déjà cuit',slot:'lunch',time:8,kcal:530,protein:42,carbs:42,fat:22,tags:['no-cook','chicken','high-protein'],image:bowlImg,ingredients:[['Poulet déjà cuit','4 oz'],['Tortilla complète','1'],['Salade romaine','1.5 cups'],['Parmesan','1 oz'],['Sauce Caesar','1 tbsp']],steps:['Émincez le poulet déjà cuit.','Mélangez avec la salade et la sauce.','Ajoutez le parmesan et roulez.'],tip:'Utilise du poulet déjà cuit ou des restes.',methods:{default:['Sans cuisson','8 min'],airfryer:['Sans cuisson','Aucune cuisson nécessaire']}},
    {id:'minimal-nocook-bean-corn',name:'Salade haricots noirs, maïs & avocat',slot:'dinner',time:10,kcal:520,protein:22,carbs:68,fat:20,tags:['no-cook','vegan','salad','mexican'],image:noCookImg,ingredients:[['Haricots noirs en conserve','¾ cup'],['Maïs en conserve','½ cup'],['Avocat','½'],['Tomates','1 cup'],['Citron vert','½']],steps:['Rincez haricots et maïs.','Coupez avocat et tomates.','Mélangez avec le citron vert.'],tip:'Dîner végétal complet sans cuisson.',methods:{default:['Sans cuisson','10 min'],airfryer:['Sans cuisson','Aucune cuisson nécessaire']}},
    {id:'minimal-nocook-cottage-bowl',name:'Bowl cottage cheese, avocat & tomates',slot:'lunch',time:5,kcal:390,protein:31,carbs:24,fat:20,tags:['no-cook','high-protein','vegetarian','quick'],image:bowlImg,ingredients:[['Cottage cheese','1 cup'],['Avocat','½'],['Tomates cerises','1 cup'],['Pain complet','1 slice']],steps:['Versez le cottage cheese dans un bol.','Ajoutez avocat et tomates.','Servez avec le pain.'],tip:'Très rapide et riche en protéines.',methods:{default:['Sans cuisson','5 min'],airfryer:['Sans cuisson','Aucune cuisson nécessaire']}},
    {id:'minimal-nocook-tofu-sesame',name:'Salade tofu fumé, concombre & sésame',slot:'dinner',time:9,kcal:460,protein:29,carbs:32,fat:24,tags:['no-cook','vegan','high-protein','salad'],image:noCookImg,ingredients:[['Tofu fumé prêt à manger','5 oz'],['Concombre','1'],['Edamame décongelé','½ cup'],['Sauce soja','1 tbsp'],['Graines de sésame','1 tsp']],steps:['Coupez le tofu et le concombre.','Ajoutez les edamame décongelés.','Assaisonnez avec soja et sésame.'],tip:'Choisissez un tofu fumé indiqué prêt à consommer.',methods:{default:['Sans cuisson','9 min'],airfryer:['Sans cuisson','Aucune cuisson nécessaire']}},
    {id:'minimal-nocook-yogurt-parfait',name:'Parfait yaourt grec, pomme & noix',slot:'breakfast',time:4,kcal:410,protein:24,carbs:42,fat:17,tags:['no-cook','breakfast','vegetarian'],image:breakfastImg,ingredients:[['Yaourt grec','1 cup'],['Pomme','1'],['Noix','1 oz'],['Cannelle','1 pinch']],steps:['Coupez la pomme.','Alternez yaourt, pomme et noix.','Ajoutez la cannelle.'],tip:'Prêt en quelques minutes.',methods:{default:['Sans cuisson','4 min'],airfryer:['Sans cuisson','Aucune cuisson nécessaire']}},

    {id:'minimal-micro-egg-mug',name:'Mug œufs, épinards & feta',slot:'breakfast',time:5,kcal:350,protein:29,carbs:9,fat:22,tags:['microwave','breakfast','high-protein','vegetarian'],image:breakfastImg,ingredients:[['Œufs','2'],['Blancs d’œufs','¼ cup'],['Épinards','½ cup'],['Feta','1 oz']],steps:['Battez les œufs dans un grand mug compatible micro-ondes.','Ajoutez épinards et feta.','Cuisez par tranches de 30 secondes en remuant jusqu’à ce que les œufs soient pris.'],tip:'Utilisez un grand récipient pour éviter les débordements.',methods:{default:['Micro-ondes','2–3 min par intervalles'],microwave:['Micro-ondes','2–3 min par intervalles']}},
    {id:'minimal-micro-oats',name:'Porridge micro-ondes banane & beurre de cacahuète',slot:'breakfast',time:6,kcal:440,protein:18,carbs:61,fat:15,tags:['microwave','breakfast','vegetarian'],image:breakfastImg,ingredients:[['Flocons d’avoine','½ cup'],['Lait','1 cup'],['Banane','½'],['Beurre de cacahuète','1 tbsp']],steps:['Mélangez avoine et lait dans un grand bol.','Cuisez 2 minutes, remuez, puis poursuivez par tranches de 30 secondes.','Ajoutez banane et beurre de cacahuète.'],tip:'Surveillez pour éviter que le lait déborde.',methods:{default:['Micro-ondes','3–4 min'],microwave:['Micro-ondes','3–4 min']}},
    {id:'minimal-micro-sweet-potato',name:'Patate douce garnie pois chiches & feta',slot:'lunch',time:12,kcal:510,protein:23,carbs:72,fat:16,tags:['microwave','vegetarian','high-fiber'],image:bowlImg,ingredients:[['Patate douce','1 medium'],['Pois chiches en conserve','½ cup'],['Feta','1 oz'],['Épinards','1 cup']],steps:['Piquez la patate douce avec une fourchette.','Cuisez-la au micro-ondes jusqu’à tendreté en la retournant à mi-cuisson.','Ouvrez et garnissez de pois chiches, feta et épinards.'],tip:'Le temps dépend beaucoup de la taille de la patate.',methods:{default:['Micro-ondes','7–10 min'],microwave:['Micro-ondes','7–10 min']}},
    {id:'minimal-micro-rice-tuna',name:'Bowl riz micro-ondes, thon & edamame',slot:'lunch',time:7,kcal:540,protein:39,carbs:66,fat:13,tags:['microwave','fish','high-protein'],image:bowlImg,ingredients:[['Riz micro-ondable','1 cup'],['Thon en conserve','1 can'],['Edamame surgelé','½ cup'],['Concombre','½'],['Sauce soja','1 tbsp']],steps:['Chauffez le riz selon l’emballage.','Chauffez les edamame au micro-ondes.','Assemblez avec le thon, concombre et sauce soja.'],tip:'Repas complet avec uniquement un micro-ondes.',methods:{default:['Micro-ondes','5–7 min'],microwave:['Micro-ondes','5–7 min']}},
    {id:'minimal-micro-mexican-rice',name:'Bowl mexicain riz, haricots & salsa',slot:'dinner',time:8,kcal:560,protein:24,carbs:86,fat:14,tags:['microwave','vegan','mexican'],image:bowlImg,ingredients:[['Riz micro-ondable','1 cup'],['Haricots noirs en conserve','¾ cup'],['Maïs en conserve','½ cup'],['Salsa','¼ cup'],['Avocat','¼']],steps:['Chauffez riz, haricots et maïs dans un récipient adapté.','Ajoutez salsa et avocat après cuisson.'],tip:'Simple, économique et sans four.',methods:{default:['Micro-ondes','4–5 min'],microwave:['Micro-ondes','4–5 min']}},
    {id:'minimal-micro-chicken-veg',name:'Bowl poulet déjà cuit, légumes vapeur & riz',slot:'dinner',time:9,kcal:570,protein:45,carbs:65,fat:14,tags:['microwave','chicken','high-protein'],image:bowlImg,ingredients:[['Poulet déjà cuit','5 oz'],['Riz micro-ondable','1 cup'],['Légumes vapeur surgelés','1.5 cups'],['Sauce soja','1 tbsp']],steps:['Chauffez le riz.','Cuisez les légumes vapeur selon l’emballage.','Réchauffez le poulet jusqu’à ce qu’il soit bien chaud et assemblez.'],tip:'Idéal avec des restes de poulet déjà cuit.',methods:{default:['Micro-ondes','6–8 min'],microwave:['Micro-ondes','6–8 min']}},
    {id:'minimal-micro-mac-cottage',name:'Pâtes express cottage cheese & épinards',slot:'dinner',time:12,kcal:520,protein:33,carbs:69,fat:13,tags:['microwave','vegetarian','high-protein'],image:bowlImg,ingredients:[['Pâtes micro-ondables','1 serving'],['Cottage cheese','½ cup'],['Épinards','1 cup'],['Parmesan','1 tbsp']],steps:['Cuisez les pâtes selon l’emballage.','Ajoutez les épinards et réchauffez 30 secondes.','Mélangez avec cottage cheese et parmesan.'],tip:'Utilisez des pâtes conçues pour cuisson micro-ondes.',methods:{default:['Micro-ondes','8–12 min'],microwave:['Micro-ondes','8–12 min']}},
    {id:'minimal-micro-baked-oat',name:'Bowl cake avoine & fruits rouges',slot:'breakfast',time:6,kcal:390,protein:21,carbs:54,fat:11,tags:['microwave','breakfast','vegetarian'],image:breakfastImg,ingredients:[['Flocons d’avoine','½ cup'],['Œuf','1'],['Lait','¼ cup'],['Fruits rouges','½ cup'],['Yaourt grec','¼ cup']],steps:['Mélangez avoine, œuf et lait dans un bol.','Ajoutez les fruits.','Cuisez par intervalles jusqu’à ce que le centre soit pris puis ajoutez le yaourt.'],tip:'Laissez reposer une minute avant de manger.',methods:{default:['Micro-ondes','2–4 min'],microwave:['Micro-ondes','2–4 min']}},
    {id:'minimal-micro-couscous-chickpea',name:'Couscous express pois chiches & légumes',slot:'lunch',time:8,kcal:500,protein:22,carbs:76,fat:14,tags:['microwave','vegan','mediterranean'],image:bowlImg,ingredients:[['Couscous','¾ cup'],['Eau','¾ cup'],['Pois chiches en conserve','½ cup'],['Légumes surgelés','1 cup'],['Citron','½']],steps:['Chauffez l’eau au micro-ondes.','Versez-la sur le couscous et couvrez quelques minutes.','Réchauffez légumes et pois chiches puis mélangez.'],tip:'Pas de casserole nécessaire.',methods:{default:['Micro-ondes','6–8 min'],microwave:['Micro-ondes','6–8 min']}},
    {id:'minimal-micro-potato-cottage',name:'Pomme de terre cottage cheese & ciboulette',slot:'dinner',time:12,kcal:450,protein:30,carbs:62,fat:10,tags:['microwave','vegetarian','high-protein'],image:bowlImg,ingredients:[['Pomme de terre','1 large'],['Cottage cheese','¾ cup'],['Épinards','1 cup'],['Ciboulette','1 tbsp']],steps:['Piquez la pomme de terre.','Cuisez-la au micro-ondes en la retournant à mi-cuisson.','Ouvrez et garnissez de cottage cheese, épinards et ciboulette.'],tip:'Vérifiez la tendreté avant de prolonger la cuisson.',methods:{default:['Micro-ondes','8–11 min'],microwave:['Micro-ondes','8–11 min']}},
    {id:'minimal-micro-apple-oats',name:'Porridge pomme cannelle protéiné',slot:'breakfast',time:6,kcal:420,protein:24,carbs:63,fat:9,tags:['microwave','breakfast','high-protein','vegetarian'],image:breakfastImg,ingredients:[['Flocons d’avoine','½ cup'],['Lait','¾ cup'],['Pomme','1'],['Skyr','½ cup'],['Cannelle','1 pinch']],steps:['Mélangez avoine, lait et pomme coupée.','Cuisez par intervalles en remuant.','Ajoutez le skyr et la cannelle après cuisson.'],tip:'Ajoutez le skyr après cuisson pour garder sa texture.',methods:{default:['Micro-ondes','3–4 min'],microwave:['Micro-ondes','3–4 min']}},
    {id:'minimal-micro-bean-quesadilla',name:'Quesadilla haricots & fromage au micro-ondes',slot:'lunch',time:6,kcal:500,protein:24,carbs:58,fat:20,tags:['microwave','vegetarian','mexican'],image:bowlImg,ingredients:[['Tortilla complète','1'],['Haricots noirs en conserve','½ cup'],['Fromage râpé','1.5 oz'],['Salsa','2 tbsp']],steps:['Écrasez légèrement les haricots sur la tortilla.','Ajoutez le fromage et repliez.','Chauffez au micro-ondes jusqu’à fromage fondu puis servez avec la salsa.'],tip:'La tortilla reste plus souple qu’avec une poêle.',methods:{default:['Micro-ondes','1–2 min'],microwave:['Micro-ondes','1–2 min']}}
  ];

  EXTRA.forEach(r=>{if(!RECIPES.some(x=>x.id===r.id))RECIPES.push(r)});

  function minimalCategory(r,cat){
    if(cat==='no-cook'){
      const method=String(r?.methods?.default?.[0]||'').toLowerCase();
      return (r?.tags||[]).includes('no-cook')||method.includes('sans cuisson')||method.includes('no cook');
    }
    if(cat==='microwave'){
      const method=String(r?.methods?.default?.[0]||'').toLowerCase();
      return (r?.tags||[]).includes('microwave')||method.includes('micro-ondes')||method.includes('microwave');
    }
    return false;
  }

  const previousRender=renderRecipes;
  renderRecipes=function(filter='all'){
    const cat=window.__recipeCategory||'all';
    if(cat!=='no-cook'&&cat!=='microwave')return previousRender(filter);
    window.__recipeFilter=filter;
    let list=RECIPES.filter(r=>eligibleByProfile(r)&&minimalCategory(r,cat));
    if(filter==='favorite')list=list.filter(r=>state.favorites.has(r.id));
    else if(filter!=='all')list=list.filter(r=>filter==='quick'?r.time<=20:(r.tags||[]).includes(filter));
    const grid=document.querySelector('#recipeGrid');if(!grid)return;
    grid.innerHTML=list.length?list.map(recipeCard).join(''):'<div class="empty-state">'+tr('Aucune recette ne correspond encore à ces filtres.','No recipe matches these filters yet.')+'</div>';
    document.querySelectorAll('[data-recipe]').forEach(el=>el.onclick=e=>{if(e.target.closest('[data-fav],[data-add-week]'))return;openRecipe(recipeById(el.dataset.recipe),tr('Carnet de recettes','Recipe book'))});
    document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();favoriteRecipe(b.dataset.fav)});
    document.querySelectorAll('[data-add-week]').forEach(b=>b.onclick=e=>{e.stopPropagation();openCalendar(recipeById(b.dataset.addWeek))});
  };

  document.querySelectorAll('[data-recipe-category="no-cook"],[data-recipe-category="microwave"]').forEach(b=>b.addEventListener('click',()=>{
    document.querySelectorAll('[data-recipe-category]').forEach(x=>x.classList.remove('active'));
    b.classList.add('active');window.__recipeCategory=b.dataset.recipeCategory;renderRecipes(window.__recipeFilter||'all');
  }));

  try{renderRecipes(window.__recipeFilter||'all')}catch{}
})();