// Kitchen Studio V3 — stability + personalization + rich recipe library
const EXTRA_RECIPES = [
{id:'herb-salmon',name:'Saumon citron herbes',slot:'dinner',time:20,kcal:560,protein:42,carbs:28,fat:27,tags:['fish','protein','high-protein','airfryer','french'],image:'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1000&q=80',ingredients:[['Filet de saumon','5 oz'],['Pommes de terre','6 oz'],['Haricots verts','1 cup'],['Citron','½']],steps:['Assaisonnez le saumon avec citron et herbes.','Cuisez les pommes de terre puis ajoutez le saumon selon votre appareil.','Servez avec les haricots verts.'],tip:'Très bon avec une sauce yaourt-citron.',methods:{default:['Four','400°F · 12–15 min'],airfryer:['Air Fry','390°F · 9–11 min']}},
{id:'cod-provencal',name:'Cabillaud à la provençale',slot:'dinner',time:24,kcal:470,protein:43,carbs:36,fat:15,tags:['fish','protein','french'],image:'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=1000&q=80',ingredients:[['Cabillaud','5 oz'],['Tomates','1 cup'],['Courgette','1'],['Olives','1 tbsp']],steps:['Coupez courgette et tomates.','Disposez le poisson au centre avec les légumes.','Cuisez jusqu’à ce que le poisson se détache facilement.'],tip:'Ajoutez du basilic juste avant de servir.',methods:{default:['Four','400°F · 14–16 min'],airfryer:['Bake','375°F · 10–13 min']}},
{id:'beef-bowl',name:'Bœuf gingembre bowl',slot:'dinner',time:18,kcal:650,protein:45,carbs:66,fat:22,tags:['meat','beef','protein','chinese','quick'],image:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=80',ingredients:[['Bœuf émincé','5 oz'],['Riz cuit','¾ cup'],['Brocoli','1 cup'],['Sauce soja','1 tbsp']],steps:['Saisissez le bœuf à feu vif.','Ajoutez brocoli, gingembre et soja.','Servez avec le riz chaud.'],tip:'Coupez le bœuf très fin pour une cuisson rapide.',methods:{default:['Wok / poêle','10–12 min'],airfryer:['Air Fry + plaques','Bœuf 400°F · 6–8 min; sauce sur plaques']}},
{id:'beef-burger',name:'Burger bœuf smash maison',slot:'dinner',time:22,kcal:720,protein:43,carbs:55,fat:35,tags:['meat','beef','american','occasion'],image:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1000&q=80',ingredients:[['Bœuf haché','5 oz'],['Pain burger','1'],['Tomate','½'],['Salade','½ cup']],steps:['Formez une boule de bœuf.','Écrasez-la sur poêle très chaude et faites dorer.','Toastez le pain et assemblez.'],tip:'Ajoutez pickles et oignon selon vos goûts.',methods:{default:['Poêle','8–10 min'],airfryer:['Air Fry','390°F · 8–10 min']}},
{id:'pork-tenderloin',name:'Filet mignon moutarde & pommes',slot:'dinner',time:30,kcal:590,protein:47,carbs:47,fat:22,tags:['meat','pork','protein','french','airfryer'],image:'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=80',ingredients:[['Filet mignon de porc','6 oz'],['Pomme','1'],['Pommes de terre','6 oz'],['Moutarde','1 tbsp']],steps:['Badigeonnez le porc de moutarde.','Ajoutez pommes et pommes de terre.','Cuisez jusqu’à température interne sûre puis laissez reposer.'],tip:'Le repos de 5 minutes garde la viande plus juteuse.',methods:{default:['Four','400°F · 22–28 min'],airfryer:['Roast','380°F · 18–22 min']}},
{id:'thai-chicken',name:'Poulet thaï coco basilic',slot:'dinner',time:24,kcal:640,protein:46,carbs:58,fat:24,tags:['meat','chicken','protein','thai'],image:'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1000&q=80',ingredients:[['Poulet','5 oz'],['Lait de coco','½ cup'],['Poivron','½'],['Riz cuit','¾ cup']],steps:['Saisissez le poulet en morceaux.','Ajoutez poivron, curry et lait de coco.','Laissez réduire puis servez sur le riz avec basilic.'],tip:'Dosez le piment séparément pour ajuster le niveau épicé.',methods:{default:['Poêle','20–24 min'],airfryer:['Air Fry + plaques','Poulet 390°F · 11–13 min; sauce sur plaques']}},
{id:'chicken-parm',name:'Chicken parmesan croustillant',slot:'dinner',time:28,kcal:690,protein:54,carbs:58,fat:24,tags:['meat','chicken','protein','italian','airfryer'],image:'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1000&q=80',ingredients:[['Blanc de poulet','5 oz'],['Chapelure','⅓ cup'],['Passata tomate','½ cup'],['Parmesan','1 oz']],steps:['Panez le poulet.','Cuisez jusqu’à croustillant.','Ajoutez tomate et parmesan puis gratinez brièvement.'],tip:'Servez avec salade ou pâtes selon votre objectif.',methods:{default:['Four','425°F · 20–24 min'],airfryer:['Air Fry','390°F · 14–17 min']}},
{id:'vegan-curry',name:'Curry vegan pois chiches & coco',slot:'dinner',time:25,kcal:590,protein:21,carbs:76,fat:22,tags:['vegan','vegetarian','thai','protein'],image:'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=1000&q=80',ingredients:[['Pois chiches','1 cup'],['Lait de coco','½ cup'],['Épinards','1 cup'],['Riz cuit','½ cup']],steps:['Faites revenir les épices.','Ajoutez pois chiches et lait de coco.','Incorporez les épinards puis servez avec riz.'],tip:'Se congèle très bien en portions individuelles.',methods:{default:['Casserole','22–25 min'],airfryer:['Plaques recommandées','Cuisson sauce sur plaques']}},
{id:'vegan-noodles',name:'Nouilles vegan sésame légumes',slot:'lunch',time:16,kcal:520,protein:19,carbs:73,fat:18,tags:['vegan','vegetarian','chinese','quick'],image:'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=1000&q=80',ingredients:[['Nouilles','3 oz'],['Brocoli','1 cup'],['Carotte','1'],['Sauce soja','1 tbsp']],steps:['Cuisez les nouilles.','Sautez les légumes rapidement.','Mélangez avec soja, sésame et nouilles.'],tip:'Ajoutez tofu ou edamame pour plus de protéines.',methods:{default:['Wok','16 min'],airfryer:['Plaques recommandées','Les nouilles sont plus adaptées au wok']}},
{id:'croque-monsieur',name:'Croque-monsieur léger',slot:'lunch',time:15,kcal:520,protein:33,carbs:48,fat:21,tags:['meat','french','quick','airfryer'],image:'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=1000&q=80',ingredients:[['Pain complet','2 tranches'],['Jambon','3 oz'],['Fromage','1 oz'],['Moutarde','1 tsp']],steps:['Montez le sandwich avec jambon, fromage et moutarde.','Cuisez jusqu’à pain doré et fromage fondu.'],tip:'Ajoutez une salade verte pour un repas complet.',methods:{default:['Poêle / four','10–12 min'],airfryer:['Air Fry','360°F · 6–8 min']}},
{id:'italian-pesto',name:'Pasta pesto poulet & tomate',slot:'dinner',time:20,kcal:700,protein:48,carbs:78,fat:22,tags:['meat','chicken','protein','italian','quick'],image:'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1000&q=80',ingredients:[['Pâtes','3 oz sec'],['Poulet','4 oz'],['Pesto','1 tbsp'],['Tomates cerises','½ cup']],steps:['Cuisez les pâtes.','Cuisez et tranchez le poulet.','Mélangez pâtes, pesto, tomates et poulet.'],tip:'Gardez un peu d’eau de cuisson pour détendre le pesto.',methods:{default:['Plaques','20 min'],airfryer:['Air Fry + plaques','Poulet 390°F · 11–13 min']}},
{id:'american-tacos',name:'Tacos poulet BBQ',slot:'lunch',time:18,kcal:610,protein:44,carbs:61,fat:20,tags:['meat','chicken','american','quick'],image:'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=1000&q=80',ingredients:[['Poulet','4 oz'],['Tortilla complète','2'],['Chou','1 cup'],['Sauce BBQ','1 tbsp']],steps:['Cuisez le poulet avec paprika.','Réchauffez les tortillas.','Assemblez avec chou et sauce BBQ.'],tip:'Ajoutez yaourt citronné pour remplacer une sauce plus riche.',methods:{default:['Poêle','16–18 min'],airfryer:['Air Fry','390°F · 11–13 min']}},
{id:'french-omelet',name:'Omelette fines herbes & chèvre',slot:'breakfast',time:10,kcal:410,protein:29,carbs:12,fat:27,tags:['breakfast','vegetarian','protein','french','quick'],image:'https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=1000&q=80',ingredients:[['Œufs','3'],['Fromage de chèvre','1 oz'],['Épinards','1 cup'],['Herbes','1 tbsp']],steps:['Battez les œufs.','Cuisez doucement en ramenant les bords vers le centre.','Ajoutez chèvre et herbes puis pliez.'],tip:'Feu doux = omelette plus tendre.',methods:{default:['Poêle','8–10 min'],airfryer:['Bake','325°F · 8–10 min dans moule']}},
{id:'breakfast-burrito',name:'Breakfast burrito protéiné',slot:'breakfast',time:15,kcal:540,protein:37,carbs:49,fat:21,tags:['breakfast','protein','american','quick'],image:'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1000&q=80',ingredients:[['Tortilla complète','1'],['Œufs','2'],['Haricots noirs','½ cup'],['Fromage','1 oz']],steps:['Brouillez les œufs.','Ajoutez haricots et fromage.','Roulez dans la tortilla et grillez légèrement.'],tip:'Préparez-en plusieurs et congelez-les.',methods:{default:['Poêle','15 min'],airfryer:['Reheat','350°F · 4–5 min']}},
{id:'berry-smoothie',name:'Smoothie fruits rouges protéiné',slot:'breakfast',time:5,kcal:360,protein:31,carbs:43,fat:7,tags:['smoothie','drink','breakfast','protein','vegetarian','quick'],image:'https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=1000&q=80',ingredients:[['Fruits rouges','1 cup'],['Skyr','¾ cup'],['Lait','½ cup'],['Banane','½']],steps:['Placez tous les ingrédients dans le blender.','Mixez jusqu’à texture lisse.'],tip:'Ajoutez glace ou lait pour ajuster la texture.',methods:{default:['Blender','1 min'],airfryer:['Sans cuisson','Aucune cuisson']}},
{id:'green-smoothie',name:'Smoothie vert mangue épinard',slot:'breakfast',time:5,kcal:300,protein:18,carbs:52,fat:4,tags:['smoothie','drink','breakfast','vegetarian','quick'],image:'https://images.unsplash.com/photo-1610970881699-44a5587cabec?auto=format&fit=crop&w=1000&q=80',ingredients:[['Mangue','1 cup'],['Épinards','1 cup'],['Skyr','½ cup'],['Lait','½ cup']],steps:['Mixez tous les ingrédients jusqu’à homogénéité.'],tip:'Le skyr rend le smoothie plus rassasiant.',methods:{default:['Blender','1 min'],airfryer:['Sans cuisson','Aucune cuisson']}},
{id:'iced-matcha',name:'Iced matcha latte',slot:'breakfast',time:4,kcal:140,protein:8,carbs:18,fat:4,tags:['drink','vegetarian','quick'],image:'https://images.unsplash.com/photo-1515823662972-da6a2e4d3002?auto=format&fit=crop&w=1000&q=80',ingredients:[['Matcha','1 tsp'],['Lait','1 cup'],['Miel','1 tsp'],['Glace','1 cup']],steps:['Fouettez le matcha avec un peu d’eau.','Ajoutez glace, lait et miel.'],tip:'Le miel est facultatif si vous choisissez peu de sucre.',methods:{default:['Sans cuisson','4 min'],airfryer:['Sans cuisson','Aucune cuisson']}},
{id:'protein-chocolate',name:'Chocolat chaud protéiné',slot:'breakfast',time:7,kcal:230,protein:25,carbs:24,fat:6,tags:['drink','protein','breakfast','quick'],image:'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&w=1000&q=80',ingredients:[['Lait','1 cup'],['Cacao','1 tbsp'],['Protéine chocolat','1 scoop']],steps:['Chauffez le lait sans bouillir.','Fouettez le cacao puis incorporez la protéine hors du feu.'],tip:'Évitez de faire bouillir après ajout de la poudre protéinée.',methods:{default:['Casserole / micro-ondes','5–7 min'],airfryer:['Sans cuisson air fryer','Utilisez casserole ou micro-ondes']}},
{id:'apple-tart',name:'Tarte fine aux pommes',slot:'dinner',time:35,kcal:390,protein:6,carbs:58,fat:16,tags:['dessert','french','occasion','vegetarian'],image:'https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?auto=format&fit=crop&w=1000&q=80',ingredients:[['Pâte feuilletée','1 portion'],['Pomme','1'],['Cannelle','1 tsp'],['Miel','1 tsp']],steps:['Étalez la pâte et disposez les pommes fines.','Saupoudrez de cannelle.','Cuisez jusqu’à pâte bien dorée.'],tip:'Parfait pour une occasion sans gâteau lourd.',methods:{default:['Four','400°F · 25–30 min'],airfryer:['Bake','350°F · 14–18 min en format individuel']}},
{id:'birthday-cake',name:'Gâteau anniversaire vanille & fruits',slot:'dinner',time:55,kcal:520,protein:8,carbs:72,fat:22,tags:['dessert','occasion','american','vegetarian'],image:'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1000&q=80',ingredients:[['Farine','1 cup'],['Œufs','2'],['Sucre','½ cup'],['Fruits rouges','1 cup']],steps:['Préparez la pâte à gâteau.','Cuisez jusqu’à lame sèche au centre.','Laissez refroidir puis décorez avec fruits et crème selon envie.'],tip:'Ajoutez l’événement à votre semaine pour inclure les ingrédients dans les courses.',methods:{default:['Four','350°F · 30–35 min'],airfryer:['Bake','320°F · 22–28 min selon moule']}},
{id:'holiday-cookies',name:'Cookies fête chocolat',slot:'dinner',time:28,kcal:310,protein:5,carbs:39,fat:16,tags:['dessert','occasion','american','vegetarian'],image:'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=1000&q=80',ingredients:[['Farine','1 cup'],['Beurre','½ cup'],['Sucre','⅓ cup'],['Chocolat','½ cup']],steps:['Mélangez la pâte.','Formez des cookies espacés.','Cuisez jusqu’à bords dorés.'],tip:'Préparez la pâte à l’avance et congelez les portions.',methods:{default:['Four','350°F · 10–12 min'],airfryer:['Bake','320°F · 7–9 min']}},
{id:'thai-shrimp',name:'Crevettes thaï citron vert',slot:'dinner',time:17,kcal:510,protein:39,carbs:55,fat:15,tags:['fish','protein','thai','quick','airfryer'],image:'https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?auto=format&fit=crop&w=1000&q=80',ingredients:[['Crevettes','6 oz'],['Riz cuit','¾ cup'],['Poivron','½'],['Citron vert','1']],steps:['Assaisonnez les crevettes avec citron vert et ail.','Cuisez rapidement jusqu’à opaques.','Servez avec riz et poivron.'],tip:'Les crevettes cuisent très vite : évitez la surcuisson.',methods:{default:['Poêle','6–8 min'],airfryer:['Air Fry','390°F · 6–8 min']}},
{id:'chinese-orange-chicken',name:'Poulet orange maison',slot:'dinner',time:25,kcal:660,protein:47,carbs:78,fat:17,tags:['meat','chicken','protein','chinese','airfryer'],image:'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=1000&q=80',ingredients:[['Poulet','5 oz'],['Riz cuit','¾ cup'],['Orange','1'],['Sauce soja','1 tbsp']],steps:['Cuisez le poulet jusqu’à doré.','Réduisez jus d’orange et soja en sauce.','Enrobez le poulet et servez avec riz.'],tip:'Contrôlez le sucre en n’ajoutant pas de sucre supplémentaire.',methods:{default:['Poêle','20–25 min'],airfryer:['Air Fry + plaques','Poulet 390°F · 12–14 min; sauce sur plaques']}},
{id:'caprese-toast',name:'Toast caprese pesto',slot:'lunch',time:10,kcal:460,protein:23,carbs:44,fat:21,tags:['vegetarian','italian','quick'],image:'https://images.unsplash.com/photo-1546549032-9571cd6b27df?auto=format&fit=crop&w=1000&q=80',ingredients:[['Pain complet','2 tranches'],['Mozzarella','2 oz'],['Tomate','1'],['Pesto','1 tbsp']],steps:['Tartinez le pain de pesto.','Ajoutez tomate et mozzarella.','Grillez jusqu’à fromage fondu.'],tip:'Ajoutez roquette après cuisson.',methods:{default:['Four / poêle','8–10 min'],airfryer:['Air Fry','360°F · 5–6 min']}}
];
RECIPES.push(...EXTRA_RECIPES.filter(x=>!RECIPES.some(r=>r.id===x.id)));

state.favorites=new Set(JSON.parse(localStorage.getItem('miseFavorites')||'[]'));
state.extraExpenses=JSON.parse(localStorage.getItem('miseExtraExpenses')||'[]');
state.account=JSON.parse(localStorage.getItem('miseAccount')||'null');
state.profile.proteinPriority=state.profile.proteinPriority||'normal';
state.profile.sugar=state.profile.sugar||'normal';
state.profile.notes=state.profile.notes||'';

const v3BaseRenderAppliances=renderAppliances;
renderAppliances=function(filter){
  if(state.profile.applianceId) appliances.forEach(a=>a.favorite=a.id===state.profile.applianceId);
  return v3BaseRenderAppliances(filter);
};
const v3BasePopulateApplianceSelect=populateApplianceSelect;
populateApplianceSelect=function(){
  v3BasePopulateApplianceSelect();
  const sel=$('#detailApplianceSelect');
  if(sel&&state.profile.applianceId&&appliances.some(a=>a.id===state.profile.applianceId)) sel.value=state.profile.applianceId;
};

function savePlan(){localStorage.setItem('misePlan',JSON.stringify(state.plan))}
function saveProfileV3(){localStorage.setItem('miseProfile',JSON.stringify(state.profile))}
function favoriteRecipe(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);localStorage.setItem('miseFavorites',JSON.stringify([...state.favorites]));renderRecipes(window.__recipeFilter||'all');renderAccount();if(currentRecipe?.id===id)syncDetailActions()}
function syncDetailActions(){if(!currentRecipe)return;const b=$('#detailFavoriteBtn');if(b)b.textContent=state.favorites.has(currentRecipe.id)?'♥ Favori':'♡ Ajouter aux favoris'}
function recipeCategory(r){
 const t=new Set(r.tags||[]);if(t.has('fish'))return'fish';if(t.has('beef'))return'beef';if(t.has('pork'))return'pork';if(t.has('chicken'))return'chicken';if(t.has('vegan'))return'vegan';if(t.has('smoothie'))return'smoothie';if(t.has('drink'))return'drink';if(t.has('breakfast')||r.slot==='breakfast')return'breakfast';if(t.has('french'))return'french';if(t.has('american'))return'american';if(t.has('chinese'))return'chinese';if(t.has('thai'))return'thai';if(t.has('italian'))return'italian';if(t.has('dessert'))return'dessert';if(t.has('occasion'))return'occasion';if(t.has('meat'))return'meat';if(t.has('protein')||t.has('high-protein'))return'protein';return'other'
}
function eligibleByProfile(r){
 const tags=new Set(r.tags||[]),diet=state.profile.diet;
 if(diet==='vegan'&&!tags.has('vegan'))return false;
 if(diet==='vegetarian'&&!(tags.has('vegetarian')||tags.has('vegan')||r.slot==='breakfast'))return false;
 if(diet==='pescatarian'&&(tags.has('meat')||tags.has('chicken')||tags.has('beef')||tags.has('pork')))return false;
 return true;
}
function scoreRecipe(r){
 let score=Math.random()*2;if((state.profile.proteinPriority==='high'||state.profile.proteinPriority==='very-high')&&(r.tags.includes('high-protein')||r.tags.includes('protein')))score+=4;if(state.profile.sugar==='low'&&(r.tags.includes('dessert')||r.tags.includes('drink')))score-=2;
 const active=appliances.find(a=>a.id===state.profile.applianceId)||appliances.find(a=>a.favorite);if(active?.type==='Air Fryer'&&r.tags.includes('airfryer'))score+=2;return score
}
function chooseDifferent(slot,current){
 const pool=RECIPES.filter(r=>r.slot===slot&&r.id!==current&&eligibleByProfile(r)).sort((a,b)=>scoreRecipe(b)-scoreRecipe(a));return (pool[0]||RECIPES.find(r=>r.slot===slot&&r.id!==current)||recipe(current)).id
}
function robustRenderWeek(){
 const grid=$('#weekGrid');if(!grid)return;grid.innerHTML='';const days=currentDays(),labels=currentMeals();
 state.plan.forEach((meals,d)=>{const col=document.createElement('div');col.className='day-col';const date=dateForDay(d);col.innerHTML=`<div class="day-head"><strong>${days[d]}</strong><small>${fmtDate(date)}</small></div>`;meals.forEach((id,s)=>{const r=recipeById(id);if(!r)return;const slot=['breakfast','lunch','dinner'][s],key=`${d}-${s}`,rt=recipeText(r);const card=document.createElement('article');card.className=`meal-card ${slot==='dinner'?'dinner':''} ${state.selected.has(key)?'selected':''}`;card.innerHTML=`<span class="selected-dot"></span><div class="meal-slot">${labels[slot]}</div><h4>${rt.name}</h4><div class="meal-foot"><span>${r.time} min · ${r.protein}g ${isEN()?'protein':'prot.'}</span><span class="kcal">${r.kcal} kcal</span></div>`;card.onclick=e=>{if(e.shiftKey){toggleSelect(key);return}openRecipe(r,`${days[d]} ${date.getDate()} · ${labels[slot]}`)};card.oncontextmenu=e=>{e.preventDefault();toggleSelect(key)};col.appendChild(card)});grid.appendChild(col)});updateWeekHeader();renderShopping();renderRecipeIdeas()
}
renderWeek=robustRenderWeek;

const oldOpenRecipe=openRecipe;
openRecipe=function(r,slot){oldOpenRecipe(r,slot);syncDetailActions()};

function recipeCard(r){
 const rt=recipeText(r),fav=state.favorites.has(r.id);return `<article class="recipe-tile rich-recipe" data-recipe="${r.id}"><div class="recipe-tile-photo" style="background-image:url('${r.image}')"><span>${r.time} min</span><button class="recipe-fav ${fav?'active':''}" data-fav="${r.id}" aria-label="Favori">${fav?'♥':'♡'}</button></div><div class="recipe-tile-body"><div class="eyebrow">${r.protein}g ${isEN()?'protein':'protéines'} · ${r.kcal} kcal</div><h3>${rt.name}</h3><div class="recipe-meta"><span>${recipeCategory(r)}</span><button class="mini-add" data-add-week="${r.id}">+ ${isEN()?'Week':'Semaine'}</button></div></div></article>`
}
renderRecipes=function(filter='all'){
 window.__recipeFilter=filter;const cat=window.__recipeCategory||'all';let list=RECIPES.filter(eligibleByProfile);
 if(filter==='favorite')list=list.filter(r=>state.favorites.has(r.id));else if(filter!=='all')list=list.filter(r=>filter==='quick'?r.time<=20:r.tags.includes(filter));
 if(cat!=='all')list=list.filter(r=>r.tags.includes(cat)||recipeCategory(r)===cat);
 const grid=$('#recipeGrid');if(!grid)return;grid.innerHTML=list.length?list.map(recipeCard).join(''):`<div class="empty-state">${isEN()?'No recipe matches these filters yet.':'Aucune recette ne correspond encore à ces filtres.'}</div>`;
 $$('[data-recipe]').forEach(el=>el.onclick=e=>{if(e.target.closest('[data-fav],[data-add-week]'))return;openRecipe(recipeById(el.dataset.recipe),txt('Carnet de recettes','Recipe book'))});
 $$('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();favoriteRecipe(b.dataset.fav)});
 $$('[data-add-week]').forEach(b=>b.onclick=e=>{e.stopPropagation();openCalendar(recipeById(b.dataset.addWeek))})
};
$$('.filter-chip').forEach(b=>b.onclick=()=>{$$('.filter-chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderRecipes(b.dataset.filter)});
$$('[data-recipe-category]').forEach(b=>b.onclick=()=>{$$('[data-recipe-category]').forEach(x=>x.classList.remove('active'));b.classList.add('active');window.__recipeCategory=b.dataset.recipeCategory;renderRecipes(window.__recipeFilter||'all')});

let calendarRecipe=null;
function openCalendar(r){calendarRecipe=r;$('#calendarRecipeTitle').textContent=`${txt('Ajouter','Add')} “${recipeText(r).name}”`;$('#calendarDay').innerHTML=currentDays().map((d,i)=>`<option value="${i}">${d}</option>`).join('');$('#calendarSlot').value=r.slot==='breakfast'?'0':r.slot==='lunch'?'1':'2';openModal($('#calendarModal'))}
$('#calendarAddForm').onsubmit=e=>{e.preventDefault();if(!calendarRecipe)return;const d=Number($('#calendarDay').value),s=Number($('#calendarSlot').value);state.plan[d][s]=calendarRecipe.id;savePlan();closeModal($('#calendarModal'));renderWeek();toast(txt('Recette ajoutée à la semaine.','Recipe added to your week.'))};
$('#detailFavoriteBtn').onclick=()=>favoriteRecipe(currentRecipe.id);
$('#detailAddWeekBtn').onclick=()=>openCalendar(currentRecipe);

$('#regenerateSelected').onclick=()=>{const keys=state.selected.size?[...state.selected]:state.plan.flatMap((_,d)=>[0,1,2].map(s=>`${d}-${s}`));keys.forEach(key=>{const [d,s]=key.split('-').map(Number),slot=['breakfast','lunch','dinner'][s];state.plan[d][s]=chooseDifferent(slot,state.plan[d][s])});state.selected.clear();savePlan();renderWeek();toast(txt(state.selected.size?'Repas recomposés.':'Semaine recomposée.','Meals regenerated.'))};

function renderExtraExpenses(){const list=$('#extraExpenseList');if(!list)return;const total=state.extraExpenses.reduce((a,x)=>a+Number(x.price||0),0);$('#extraTotal').textContent=money(total);list.innerHTML=state.extraExpenses.map((x,i)=>`<div class="extra-row"><span><strong>${x.name}</strong><small>${money(Number(x.price))}</small></span><button data-extra-remove="${i}" aria-label="Supprimer">×</button></div>`).join('');$$('[data-extra-remove]').forEach(b=>b.onclick=()=>{state.extraExpenses.splice(Number(b.dataset.extraRemove),1);localStorage.setItem('miseExtraExpenses',JSON.stringify(state.extraExpenses));renderExtraExpenses();updateShoppingMeta();renderAccount()});updateShoppingMeta()}
$('#extraExpenseForm').onsubmit=e=>{e.preventDefault();const name=$('#extraExpenseName').value.trim(),price=Number($('#extraExpensePrice').value);if(!name||!Number.isFinite(price))return;state.extraExpenses.push({name,price});localStorage.setItem('miseExtraExpenses',JSON.stringify(state.extraExpenses));e.target.reset();renderExtraExpenses();renderAccount()};
const v2UpdateShoppingMeta=updateShoppingMeta;
updateShoppingMeta=function(){const grocery=estimatedCartTotal(),extras=state.extraExpenses.reduce((a,x)=>a+Number(x.price||0),0),total=grocery+extras;$('#pantryCount').textContent=state.checked.size;renderMoneyBig(total);$('#budgetEstimate').textContent=`≈ ${money(grocery)}`;let row=$('#extraSummaryLine');if(!row){const btn=$('#shopRealProducts2');row=document.createElement('div');row.className='summary-line';row.id='extraSummaryLine';btn.parentNode.insertBefore(row,btn)}row.innerHTML=`<span>${txt('Extra dépenses','Extra expenses')}</span><strong>${money(extras)}</strong>`;if($('#extraTotal'))$('#extraTotal').textContent=money(extras)}
const v2RenderShopping=renderShopping;
renderShopping=function(){v2RenderShopping();renderExtraExpenses()};

$('#personalQuestionsBtn').onclick=()=>{const f=$('#personalQuestionsForm');f.elements.diet.value=state.profile.diet||'balanced';f.elements.proteinPriority.value=state.profile.proteinPriority||'normal';f.elements.sugar.value=state.profile.sugar||'normal';f.elements.goal.value=state.profile.goal||'balanced';f.elements.allergies.value=state.profile.allergies||'';f.elements.notes.value=state.profile.notes||'';openModal($('#personalQuestionsModal'))};
$('#personalQuestionsForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);['diet','proteinPriority','sugar','goal','allergies','notes'].forEach(k=>state.profile[k]=fd.get(k)||'');saveProfileV3();closeModal($('#personalQuestionsModal'));renderRecipes();toast(txt('Préférences personnelles enregistrées.','Personal preferences saved.'))};

function renderAccount(){const a=state.account;$('#accountFavoriteCount').textContent=state.favorites.size;$('#accountExtraCount').textContent=state.extraExpenses.length;const ap=appliances.find(x=>x.id===state.profile.applianceId)||appliances.find(x=>x.favorite);$('#accountAppliance').textContent=ap?ap.brand:'—';if(!a)return;$('#accountName').value=a.name||'';$('#accountEmail').value=a.email||'';$('#accountDisplayName').textContent=a.name;$('#accountDisplayEmail').textContent=a.email;$('#accountAvatar').textContent=(a.name||'M')[0].toUpperCase();$('.avatar').textContent=(a.name||'M')[0].toUpperCase();$('.profile-mini strong').textContent=a.name}
$('#accountForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);state.account={name:String(fd.get('name')||'').trim(),email:String(fd.get('email')||'').trim()};localStorage.setItem('miseAccount',JSON.stringify(state.account));renderAccount();toast(txt('Compte mémorisé sur cet appareil.','Account remembered on this device.'))};

let applianceImageData=null;
$('#appliancePhotoInput').onchange=()=>{const file=$('#appliancePhotoInput').files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{applianceImageData=reader.result;$('#appliancePhotoPreview').innerHTML=`<img src="${applianceImageData}" alt="Photo appareil"><small>${file.name}</small>`;$('#recognizeApplianceBtn').disabled=false};reader.readAsDataURL(file)};
$('#recognizeApplianceBtn').onclick=async()=>{if(!applianceImageData)return;const result=$('#applianceRecognitionResult');result.hidden=false;result.innerHTML='<strong>✦ Analyse en cours…</strong>';try{const catalog=appliances.filter(a=>a.type==='Air Fryer').map(a=>({id:a.id,brand:a.brand,model:a.model}));const r=await fetch('/api/recognize-appliance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({imageDataUrl:applianceImageData,catalog})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Recognition unavailable');const match=appliances.find(a=>a.id===d.matchId);if(match){appliances.forEach(a=>a.favorite=false);match.favorite=true;state.profile.applianceId=match.id;saveProfileV3();result.innerHTML=`<div class="recognition-match"><span>✓</span><div><small>${Math.round((d.confidence||0)*100)}% confiance</small><strong>${match.brand} ${match.model}</strong><p>${d.visibleEvidence||''}</p></div></div>`;renderAppliances();populateApplianceSelect();renderAccount()}else{result.innerHTML=`<div class="recognition-match tentative"><span>?</span><div><small>${Math.round((d.confidence||0)*100)}% confiance · à confirmer</small><strong>${d.brand||'Appareil'} ${d.model||''}</strong><p>${d.visibleEvidence||txt('Modèle non présent dans la bibliothèque vérifiée.','Model is not yet in the verified library.')}</p></div></div>`}}catch(err){result.innerHTML=`<strong>${txt('Reconnaissance IA non disponible. Vérifiez la configuration AI Gateway.','AI recognition unavailable. Check AI Gateway configuration.')}</strong>`}};

const baseNavigate=navigate;
navigate=function(page){baseNavigate(page);if(page==='account')renderAccount();if(page==='recipes')renderRecipes(window.__recipeFilter||'all')};
$$('[data-page]').forEach(b=>{b.onclick=()=>navigate(b.dataset.page)});

renderRecipes();renderExtraExpenses();renderAccount();robustRenderWeek();
